#!/usr/bin/python3

import os

file_list = [
"_traverse_module.c",
"_traverse_start_clause.c",
"_traverse_module_item.c",
"_traverse_include_statement.c",
"_traverse_import_statement.c",
"_traverse_namespace_item.c",
"_traverse_global_scope_operator.c",
"_traverse_class_scope_operator.c",
"_traverse_namespace.c",
"_traverse_class_definition.c",
"_traverse_inheritance_item.c",
"_traverse_class_item.c",
"_traverse_function_declaration.c",
"_traverse_constructor_declaration.c",
"_traverse_destructor_declaration.c",
"_traverse_function_definition_parameters.c",
"_traverse_function_decl_parameter.c",
"_traverse_function_declaration_parameters.c",
"_traverse_type_specifier.c",
"_traverse_function_definition.c",
"_traverse_constructor_definition.c",
"_traverse_destructor_definition.c",
"_traverse_data_declaration.c",
"_traverse_compound_name.c",
"_traverse_const_value.c",
"_traverse_literal_string.c",
"_traverse_formatted_string.c",
"_traverse_literal_array_definition.c",
"_traverse_literal_dict_item.c",
"_traverse_literal_dict_definition.c",
"_traverse_primary_expression.c",
"_traverse_expression.c",
"_traverse_compound_reference.c",
"_traverse_compound_reference_item.c",
"_traverse_function_reference.c",
"_traverse_array_reference.c",
"_traverse_array_parameters.c",
"_traverse_function_body_item.c",
"_traverse_raise_statement.c",
"_traverse_flow_statement.c",
"_traverse_loop_body_item.c",
"_traverse_yield_statement.c",
"_traverse_loop_body.c",
"_traverse_function_body.c",
"_traverse_assignment.c",
"_traverse_data_definition.c",
"_traverse_return_statement.c",
"_traverse_if_clause.c",
"_traverse_else_clause.c",
"_traverse_final_else_clause.c",
"_traverse_for_clause.c",
"_traverse_while_clause.c",
"_traverse_do_clause.c",
"_traverse_try_clause.c",
"_traverse_except_clause.c",
"_traverse_finally_clause.c",
"_traverse_exit_statement.c",
"_traverse_inline_statement.c",
"_traverse_break_statement.c",
"_traverse_continue_statement.c",
"_traverse_literal_number.c",
"_traverse_string_literal.c",
"_traverse_literal_type.c",
"_traverse_identifier.c"
]

for name in file_list:
    with open("./src/ast/"+name, "w") as fp:
        fp.write("\n")

